MvcMusicStore/Controllers/HomeController.cs
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public string Index()
        {
            return "Hello from home";
        }
    }
}

MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Model;
using MvcMusicStore.Service;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            var genres = new List<Genre>
            {
                new Genre
                {
                    Name = "Disco"
                },
                new Genre
                {
                    Name ="Jazz"
                },
                new Genre
                {
                    Name = "Rock"
                }
            };
            return View(genres);
        }

        public ActionResult Browse(string genre)
        {
            var genreService = new GenreService();
            return View(genreService.Get(genre));
        }



        public ActionResult Details(int id)
        {
            var albumService = new AlbumService();
          Album album =   albumService.Get(id);
            return View(album);
        }
    }
}

MvcMusicStore/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Model;
using MvcMusicStore.Service;

namespace MvcMusicStore.Controllers
{
    public class StoreManagerController : Controller
    {

        private readonly AlbumService _albumService = new AlbumService();
        // GET: StoreManager
        public ActionResult Index()
        {

            List<Album> albums = _albumService.GetAll();
            return View(albums);
        }

        public ActionResult Details(int id)
        {
            Album album = _albumService.Get(id);
            return View(album);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Album album = _albumService.Get(id);
            return View(album);
        }
        [HttpPost]
        public ActionResult Delete(Album model)
        {
            _albumService.Delete(model);
            return RedirectToAction("Index");
        }
    }


    //public ActionResult Create()
    //{
    //    return View();
    //}

}

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap-Slate.min.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MvcMusicStore/Views/Store/Browse.cshtml
@model MvcMusicStore.Model.Genre
@{
    ViewBag.Title = "Browse";
}

<h2>Browsing Genre : @Model.Name</h2>
<ul class="list-group">

    @foreach (var album in Model.Albums)
    {
        <li class="list-group-item">
            @Html.ActionLink(album.Title, "Details", new { id = album.AlbumId })
        </li>
    }
</ul>

MvcMusicStore/Views/Store/Details.cshtml
@model MvcMusicStore.Model.Album
@{
    ViewBag.Title = "Details";
}

<h2>Album:@Model.Title</h2>

MvcMusicStore/Views/Store/Index.cshtml
@model IEnumerable<MvcMusicStore.Model.Genre>
@{
    ViewBag.Title = "Index";
}

<h3>Browse Genre</h3>

<p>Selecet from @Model.Count()</p>
<ul>
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name, "Browse", new
    {
        genre = genre.Name
    })
    </li>
    }
</ul>

MvcMusicStore/Views/StoreManager/Delete.cshtml
@model MvcMusicStore.Model.Album
@{
    ViewBag.Title = "Delete";
}

<h2>Are Sure To Delete?</h2>

<dl class="dl-horizontal">
    <dt>Genre</dt>
    <dd>@Html.DisplayFor(m => m.Genre.Name)</dd>

    <dt>@Html.DisplayNameFor(m => m.Artist)</dt>
    <dd>@Html.DisplayFor(m => m.Artist.Name)</dd>



    <dt>@Html.DisplayNameFor(m => m.Title)</dt>
    <dd>@Html.DisplayFor(m => m.Title)</dd>
</dl>



@using (Html.BeginForm("Delete", "StoreManager", FormMethod.Post))
{
    @Html.HiddenFor(m => m.AlbumId)
    <input type="submit" value="Submit" />
}

MvcMusicStore/Views/StoreManager/Details.cshtml
@model MvcMusicStore.Model.Album
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<dl class="dl-horizontal">
    <dt>Genre:</dt>
    <dd>@Model.Genre.Name</dd>
    <dt>Artist:</dt>
    <dd>@Model.Artist.Name</dd>
    <dt>Title:</dt>
    <dd>@Model.Title</dd>
    <dt>Price:</dt>
    <dd>@Model.Price</dd>
</dl>

MvcMusicStore/Views/StoreManager/Index.cshtml
@model IEnumerable<MvcMusicStore.Model.Album>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table table-condensed table-striped table-hover">
    <thead>
        <tr>

            <th>Genre</th>
            <th>Artist</th>
            <th>Title</th>
            <th>Price</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var album in @Model)
        {

            <tr>
                <td> @album.Genre.Name</td>
                <td> @album.Artist.Name</td>
                <td> @album.Title</td>
                <td> @album.Price</td>
                <td>
                    @Html.ActionLink(" ", "Edit", new { id = album.AlbumId },
                   new { @class = "glyphicon glyphicon-edit", title = "Edit" })
                    @Html.ActionLink("Details", "Details", new { id = album.AlbumId })
                    @Html.ActionLink(" ", "Delete", new { id = album.AlbumId },
                   new { @class = "glyphicon glyphicon-trash", title = "Delete" })
                </td>
            </tr>
        }
    </tbody>
</table>